### PR TITLE
Feature/options

### PR DESCRIPTION
**Pull request by vyorkin**
there is a problem when you try to open a file from url
in which case it doesn't have an extension.

`roo` gem has the ability to force specific spreadsheet type,
so i've added the `:filetype` option which can be used to set file type
manually.

also i've extracted explicit arguments to options hash,
tests are included

### CODE REVIEW

**Comment by jumph4x** [comment]
Thank you for the good work! Does this warrant a dot- or a minor release?

**Comment by jumph4x** [comment]
Just noticed, the README needs and update as well. I'll try to remember to take care of that...

**Comment by vyorkin** [comment]
According to [semantic versioning](http://semver.org/) the initial version should be `0.1.0` not `0.0.1`, thre reason is that we don't start with a patch, but with some initial set of features. Versions below `1.0.0` are basically the development rush, so before `1.0.0` we shouldn't worry too much about breaking things. When `1.0.0` is reached it should be considered stable & with each backwards-incompatible public api change we should increment the major version

**Comment by vyorkin** [comment]
I've just sent another PR related to #3

**Comment by jumph4x** [comment]
My bad. I will make this a 0.1.0.

**Comment by jumph4x** [comment]
Addressed and re-released: https://rubygems.org/gems/batch_factory

**Comment by vyorkin** [comment]
cool, thanks

**Pull request merged**
